language: objective-c
osx_image: xcode7
notifications:
  email: false
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -project MutableCollectionProperty.xcodeproj -scheme "MutableCollectionProperty" -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO | xcpretty -c
