language: objective-c
osx_image: xcode7
notifications:
  email: false
script:
- xcodebuild test -project MutableCollectionProperty.xcodeproj -scheme "MutableCollectionPropertyTests" -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO
